# Generated by Django 4.1.7 on 2023-09-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
