# Generated by Django 4.2.5 on 2023-09-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
