# Generated by Django 4.2.5 on 2023-09-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_phrase_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='created_at',
        ),
    ]
