# Generated by Django 4.2.5 on 2023-09-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_phrase_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='valid',
        ),
    ]
