# Generated by Django 4.2.4 on 2023-10-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_phrase_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='idUser',
        ),
    ]
