# Generated by Django 4.2.4 on 2023-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_author_blogpost_iduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('picture', models.ImageField(blank='True', null='True', upload_to='profilepics')),
            ],
        ),
    ]
