# Generated by Django 4.2.4 on 2023-10-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_author_blogpost_iduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=14)),
                ('response', models.CharField(max_length=14)),
                ('text', models.TextField()),
            ],
        ),
    ]
