# Generated by Django 4.2.4 on 2023-10-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_userdetails_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='banner',
            field=models.ImageField(blank='True', null='True', upload_to='profilebanners'),
            preserve_default='True',
        ),
    ]
