# Generated by Django 4.2.5 on 2023-10-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_chatbot'),
        ('base', '0014_userdetails_banner'),
    ]

    operations = [
    ]
