# Generated by Django 4.1.7 on 2023-10-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_merge_0012_chatbot_0014_userdetails_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='profilebanners'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics'),
        ),
    ]
