# Generated by Django 4.2.4 on 2023-10-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_userdetails_banner_alter_userdetails_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='bio',
        ),
    ]
